### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by zhenfei121** [thu-pacman/RisGraph#3]
Dear author, I have been studying your code for a month, but I still can't run your code. Could you give me a more detailed installation instructions ？Thank you very much.

**Comment by jiguanglizipao** [comment]
We have updated the README.

**Comment by hheizit** [comment]
Dear author,

Thank you for updating the instructions. Following your steps, I still have some questions about how to compile RisGraph successfully. It would be greatly appreciated if you could provide some detailed information:
- It seems that the oneTBB (https://github.com/oneapi-src/oneTBB) could not pass the FindTBB.cmake check. In fact we also tried TBB/2021.5 with no luck. TBB/2020.3 seems to be working, but we got some error/warning messages like

> /opt/linux/rocky/8.x/x86_64/pkgs/tbb/2020.3/tbb/include/tbb/tbb.h:21:154: note: #pragma message: TBB Warning: tbb.h contains deprecated functionality. For details, please see Deprecated Features appendix in the TBB reference manual.
 #pragma message("TBB Warning: tbb.h contains deprecated functionality. For details, please see Deprecated Features appendix in the TBB reference manual.")

Could you specify which TBB version is used in the project?

- We also got an error about boost:

> No rule to make target '/opt/linux/rocky/8.x/x86_64/pkgs/boost/1.78.0/lib/libboost_fiber.a'

Is this something about the boost version? We are using boost 1.78. 

Thank you very much for your help!

**Comment by zhenfei121** [comment]
好的，收到

**Comment by jiguanglizipao** [comment]
- TBB updates its native cmake supports in its new version, so you can try deleting `FindTBB.cmake` and using `find_package(TBB REQUIRED)` directly.
- With TBB/2020.3, the warning message is also caused by the TBB updates. I think you can ignore these warnings first.
- Did you install boost fiber, such as `libboost-fiber-dev` or `boost-fiber`? Boost fiber is not header-only, so it requires a pre-built library. It seems cmake cannot find the library. 
- RisGraph was tested with Ubuntu 18.04. And these dependencies are installed via `apt-get`.

**Comment by hheizit** [comment]
> * TBB updates its native cmake supports in its new version, so you can try deleting `FindTBB.cmake` and using `find_package(TBB REQUIRED)` directly.
> * With TBB/2020.3, the warning message is also caused by the TBB updates. I think you can ignore these warnings first.
> * Did you install boost fiber, such as `libboost-fiber-dev` or `boost-fiber`? Boost fiber is not header-only, so it requires a pre-built library. It seems cmake cannot find the library.
> * RisGraph was tested with Ubuntu 18.04. And these dependencies are installed via `apt-get`.

Thank you very much for the reply! 
I could compile and run RisGraph on a local Ubuntu 18.04 machine with all dependencies installed via `apt-get`. 
The previous issues might be because of the environmental setting on a HPC node where I tried to run RisGraph and I am trying to fix that.  
Thanks again.
